name: "assign_project"

on:
  repository_dispatch:
    types:
      - issue_opened
      - issue_reopened

permissions:
  pull-requests: write
  issues: write

concurrency:
  group: issue-${{ github.event.client_payload.number }}

jobs:
  main:
    uses: roc-streaming/ci/.github/workflows/project_assign.yml@main
    with:
      number: ${{ github.event.client_payload.number }}
      project: 8
    secrets:
      triage-token: ${{ secrets.REPO_TRIAGE }}
