name: build

on:
  pull_request:
    branches:
      - main
      - v*

  push:
    branches:
      - main
      - v*
    tags:
      - v*

  repository_dispatch:
  workflow_dispatch:

  schedule:
    - cron: '0 0 * * 1'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: Linux - Go 1.22
            go: '1.22'

          - name: Linux - Go 1.x
            go: '1.x'

    name: ${{ matrix.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: |
          make
