name: "build"

on:
  pull_request:
    branches:
      - main
      - v*

  push:
    branches:
      - main
      - v*
    tags:
      - v*

  # triggered from roc-toolkit
  repository_dispatch:
    types:
      - trigger_build

  workflow_dispatch:

  schedule:
    - cron: '0 0 * * 1'

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt

      - name: Run tests
        run: cargo test --all-features

      - name: Check formatting
        uses: actions-rust-lang/rustfmt@v1
