name: "pr_opened"

on:
  repository_dispatch:
    types:
      - pull_request_opened
      - pull_request_reopened

permissions:
  pull-requests: write
  checks: read

concurrency:
  group: pr-${{ github.event.client_payload.pr_number }}

jobs:
  main:
    uses: roc-streaming/ci/.github/workflows/pr_handle_opened.yml@main
    with:
      pr-number: ${{ github.event.client_payload.pr_number }}
    secrets:
      triage-token: ${{ secrets.REPO_TRIAGE }}
