name: "pr_reviewed"

on:
  repository_dispatch:
    types:
      - pull_request_review_submitted

permissions:
  pull-requests: write

concurrency:
  group: pr-${{ github.event.client_payload.pr_number }}

jobs:
  main:
    uses: roc-streaming/ci/.github/workflows/pr_handle_reviewed.yml@main
    with:
      pr-number: ${{ github.event.client_payload.pr_number }}
    secrets:
      triage-token: ${{ secrets.REPO_TRIAGE }}
