name: "pr_reviewed"

on:
  # triggered from webhook
  repository_dispatch:
    types:
      - pull_request_review

permissions:
  pull-requests: write

concurrency:
  group: pr-${{ github.event.client_payload.pr_number }}

jobs:
  main:
    uses: roc-streaming/ci/.github/workflows/pr_status_on_review.yml@main
    with:
      pr-number: ${{ github.event.client_payload.pr_number }}
    secrets:
      triage-token: ${{ secrets.REPO_MANAGEMENT }}
