name: "pr_wip"

on:
  pull_request_target:
    types:
      - review_request_removed
      - converted_to_draft

permissions:
  pull-requests: write

concurrency:
  group: pr-${{ github.event.pull_request.number }}

jobs:
  main:
    uses: roc-streaming/ci/.github/workflows/pr_status_on_wip.yml@main
